### ISSUE TITLE
gem install lagotto-rb

### ISSUE THREAD

**Issue by ankurpohekar** [lagotto/lagotto-rb#14]
gem install lagotto-rb bundle install command showing this error

ERROR:  Could not find a valid gem 'lagotto-rb' (>= 0) in any repository

**Comment by sckott** [comment]
Sorry, i had the instructions in readme, but it's not up on rubygems yet. will do that asap

**Comment by sckott** [comment]
its up now on rubygems, try `gem install lagotto-rb` now
