### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by Gauravdhandre** [lagotto/lagotto-rb#16]
getting this error continuously when i am trying to run for facebook

**Comment by sckott** [comment]
what version are you using, and put in the code you tried as well

**Comment by Gauravdhandre** [comment]
I am new in ROR and i am Using Lagotto 4.3 version , but continuously getting  "ArgumentError".

**Comment by Gauravdhandre** [comment]
Now I am Getting Input/output error @ io_write - <STDERR> for facebook . Please help me..
![facebook](https://cloud.githubusercontent.com/assets/16300277/12535391/a5588436-c2a7-11e5-825b-d0a48d38af16.png)

**Comment by sckott** [comment]
You are looking for help with Lagotto the application. This is a Ruby gem to use the API from that application. Go to https://github.com/lagotto/lagotto or http://discuss.lagotto.io/ -  closing
