### ISSUE TITLE
Bad Authentication

### ISSUE THREAD

**Issue by Gauravdhandre** [lagotto/lagotto-rb#17]
Bad Authentication data.. Getting this for Twitter.

**Comment by sckott** [comment]
what version are you using, and put in the code you tried as well

**Comment by Gauravdhandre** [comment]
I am using Lagotto 4.3

**Comment by sckott** [comment]
i think you are looking for help with Lagotto the application. This is a Ruby gem to use the API from that application. Go to https://github.com/lagotto/lagotto or http://discuss.lagotto.io/ -  closing
