### ISSUE TITLE
SocketError

### ISSUE THREAD

**Issue by Gauravdhandre** [lagotto/lagotto-rb#20]
I am Cloning lagotto on Desktop, When i am try to show  "Active Source" View it give me. 

  CACHE (0.0ms)  SELECT COUNT(*) FROM `api_responses` WHERE `api_responses`.`source_id` = 46 AND (`api_responses`.`created_at` BETWEEN '2016-01-28 07:00:00' AND '2016-01-29 07:00:00')  [["source_id", 46]]
Cache read: facebook/response_count/2016-01-29T06:35:39Z
Dalli::Server#connect lagotto.local:11211
lagotto.local:11211 failed (count: 470) SocketError: Hostname not known: lagotto.local
lagotto.local:11211 is still down (for 1002.975 seconds now)
DalliError: No server available
0
On terminal.
What shouid i do. Please help me.

**Comment by sckott** [comment]
open here https://github.com/lagotto/lagotto/issues instead
